pool:
  vmImage: vs2017-win2016

variables:
  solution: './ClientLibrary/Samples/ClientSamples.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install command'

- script: |
    npm update
  displayName: 'npm update command'

- script: |
    npm install python
  displayName: 'Install python command'

- script: |
    npm install python3
  displayName: 'Install python command'

- script: |
    npm install pip
  displayName: 'Install pip command'

- script: |
    npm install pip3
  displayName: 'Install pip3 command'

- script: |
    npm install trufflehog
  displayName: 'Install trufflehog command'

- script: |
    npm install owasp-dependency-check
  displayName: 'Install owasp-dependency-check command'

- script: |
    npm install static-code-analysis
  displayName: 'Install static-code-analysis command'

# - script: |
#     npm test
#   displayName: 'npm test command'
  
    
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish aritfacts: drop'